//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyTeamApp.EntityFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ImportEntities : DbContext
    {
        public ImportEntities()
            : base("name=ImportEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CUM> CUMs { get; set; }
        public virtual DbSet<DanhMucThietBi> DanhMucThietBis { get; set; }
        public virtual DbSet<Head> Heads { get; set; }
        public virtual DbSet<LICHSU> LICHSUs { get; set; }
        public virtual DbSet<LoaiKetNoi> LoaiKetNois { get; set; }
        public virtual DbSet<LOAITHIETBI> LOAITHIETBIs { get; set; }
        public virtual DbSet<LOAITHIETBI_TRANGTHAI> LOAITHIETBI_TRANGTHAI { get; set; }
        public virtual DbSet<MAYTINH> MAYTINHs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<THIETBI> THIETBIs { get; set; }
        public virtual DbSet<TRAM> TRAMs { get; set; }
        public virtual DbSet<TRANGTHAI> TRANGTHAIs { get; set; }
        public virtual DbSet<TRANGTHAITB> TRANGTHAITBs { get; set; }
    
        public virtual ObjectResult<GetData_Viet_Result> GetData_Viet()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetData_Viet_Result>("GetData_Viet");
        }
    
        public virtual ObjectResult<getSTATUS_Result> getSTATUS(string macum)
        {
            var macumParameter = macum != null ?
                new ObjectParameter("macum", macum) :
                new ObjectParameter("macum", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getSTATUS_Result>("getSTATUS", macumParameter);
        }
    
        public virtual ObjectResult<GetThongTinLichSuTrangThaiThietBi_Result> GetThongTinLichSuTrangThaiThietBi(string maMT)
        {
            var maMTParameter = maMT != null ?
                new ObjectParameter("MaMT", maMT) :
                new ObjectParameter("MaMT", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetThongTinLichSuTrangThaiThietBi_Result>("GetThongTinLichSuTrangThaiThietBi", maMTParameter);
        }
    
        public virtual ObjectResult<GetThongTinTrangThaiChiTietCuaThietBi_Result> GetThongTinTrangThaiChiTietCuaThietBi(string maTB)
        {
            var maTBParameter = maTB != null ?
                new ObjectParameter("MaTB", maTB) :
                new ObjectParameter("MaTB", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetThongTinTrangThaiChiTietCuaThietBi_Result>("GetThongTinTrangThaiChiTietCuaThietBi", maTBParameter);
        }
    
        public virtual ObjectResult<GetThongTinTrangThaiThietBi_Result> GetThongTinTrangThaiThietBi(string mSCum)
        {
            var mSCumParameter = mSCum != null ?
                new ObjectParameter("MSCum", mSCum) :
                new ObjectParameter("MSCum", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetThongTinTrangThaiThietBi_Result>("GetThongTinTrangThaiThietBi", mSCumParameter);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<SP_GetDataChiTietTrangThaiThietBi_Result> SP_GetDataChiTietTrangThaiThietBi(string maMT, Nullable<System.DateTime> thoiGian)
        {
            var maMTParameter = maMT != null ?
                new ObjectParameter("MaMT", maMT) :
                new ObjectParameter("MaMT", typeof(string));
    
            var thoiGianParameter = thoiGian.HasValue ?
                new ObjectParameter("ThoiGian", thoiGian) :
                new ObjectParameter("ThoiGian", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetDataChiTietTrangThaiThietBi_Result>("SP_GetDataChiTietTrangThaiThietBi", maMTParameter, thoiGianParameter);
        }
    
        public virtual ObjectResult<SP_GetDataMayTinh_Result> SP_GetDataMayTinh(string mSCum)
        {
            var mSCumParameter = mSCum != null ?
                new ObjectParameter("MSCum", mSCum) :
                new ObjectParameter("MSCum", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetDataMayTinh_Result>("SP_GetDataMayTinh", mSCumParameter);
        }
    
        public virtual ObjectResult<SP_GetDataThietBi_Result> SP_GetDataThietBi(string mSCum)
        {
            var mSCumParameter = mSCum != null ?
                new ObjectParameter("MSCum", mSCum) :
                new ObjectParameter("MSCum", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetDataThietBi_Result>("SP_GetDataThietBi", mSCumParameter);
        }
    
        public virtual ObjectResult<Nullable<System.DateTime>> SP_GetDataThoiGianLichSu()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.DateTime>>("SP_GetDataThoiGianLichSu");
        }
    
        public virtual ObjectResult<SP_GetDataTrangThaiThietBi_Result> SP_GetDataTrangThaiThietBi(string maMT)
        {
            var maMTParameter = maMT != null ?
                new ObjectParameter("MaMT", maMT) :
                new ObjectParameter("MaMT", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetDataTrangThaiThietBi_Result>("SP_GetDataTrangThaiThietBi", maMTParameter);
        }
    
        public virtual ObjectResult<SP_GetHeader_VIET_Result> SP_GetHeader_VIET(string mSCum)
        {
            var mSCumParameter = mSCum != null ?
                new ObjectParameter("MSCum", mSCum) :
                new ObjectParameter("MSCum", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetHeader_VIET_Result>("SP_GetHeader_VIET", mSCumParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SP_GetStatusComputer(string mSCum)
        {
            var mSCumParameter = mSCum != null ?
                new ObjectParameter("MSCum", mSCum) :
                new ObjectParameter("MSCum", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SP_GetStatusComputer", mSCumParameter);
        }
    
        public virtual ObjectResult<SP_GetStatusComputer_Viet_Result> SP_GetStatusComputer_Viet(string mSCum)
        {
            var mSCumParameter = mSCum != null ?
                new ObjectParameter("MSCum", mSCum) :
                new ObjectParameter("MSCum", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetStatusComputer_Viet_Result>("SP_GetStatusComputer_Viet", mSCumParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual ObjectResult<sp_Search_Result> sp_Search(string keyword)
        {
            var keywordParameter = keyword != null ?
                new ObjectParameter("Keyword", keyword) :
                new ObjectParameter("Keyword", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Search_Result>("sp_Search", keywordParameter);
        }
    
        public virtual int sp_SUP_InsertEtagThang(string maETag, string giaVe, string maLoaiVe, string soXe, Nullable<System.DateTime> ngayBatDau, Nullable<System.DateTime> ngayKetThuc, string maNhanVien, Nullable<System.DateTime> ngayBan)
        {
            var maETagParameter = maETag != null ?
                new ObjectParameter("MaETag", maETag) :
                new ObjectParameter("MaETag", typeof(string));
    
            var giaVeParameter = giaVe != null ?
                new ObjectParameter("GiaVe", giaVe) :
                new ObjectParameter("GiaVe", typeof(string));
    
            var maLoaiVeParameter = maLoaiVe != null ?
                new ObjectParameter("MaLoaiVe", maLoaiVe) :
                new ObjectParameter("MaLoaiVe", typeof(string));
    
            var soXeParameter = soXe != null ?
                new ObjectParameter("SoXe", soXe) :
                new ObjectParameter("SoXe", typeof(string));
    
            var ngayBatDauParameter = ngayBatDau.HasValue ?
                new ObjectParameter("NgayBatDau", ngayBatDau) :
                new ObjectParameter("NgayBatDau", typeof(System.DateTime));
    
            var ngayKetThucParameter = ngayKetThuc.HasValue ?
                new ObjectParameter("NgayKetThuc", ngayKetThuc) :
                new ObjectParameter("NgayKetThuc", typeof(System.DateTime));
    
            var maNhanVienParameter = maNhanVien != null ?
                new ObjectParameter("MaNhanVien", maNhanVien) :
                new ObjectParameter("MaNhanVien", typeof(string));
    
            var ngayBanParameter = ngayBan.HasValue ?
                new ObjectParameter("NgayBan", ngayBan) :
                new ObjectParameter("NgayBan", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_SUP_InsertEtagThang", maETagParameter, giaVeParameter, maLoaiVeParameter, soXeParameter, ngayBatDauParameter, ngayKetThucParameter, maNhanVienParameter, ngayBanParameter);
        }
    
        public virtual int sp_SYNC_UpdateTRANGTHAITBTable(Nullable<int> iD, string mATB, Nullable<System.DateTime> tHOIGIAN, string mOTA, Nullable<double> tRANGTHAI, string mATRANGTHAI)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var mATBParameter = mATB != null ?
                new ObjectParameter("MATB", mATB) :
                new ObjectParameter("MATB", typeof(string));
    
            var tHOIGIANParameter = tHOIGIAN.HasValue ?
                new ObjectParameter("THOIGIAN", tHOIGIAN) :
                new ObjectParameter("THOIGIAN", typeof(System.DateTime));
    
            var mOTAParameter = mOTA != null ?
                new ObjectParameter("MOTA", mOTA) :
                new ObjectParameter("MOTA", typeof(string));
    
            var tRANGTHAIParameter = tRANGTHAI.HasValue ?
                new ObjectParameter("TRANGTHAI", tRANGTHAI) :
                new ObjectParameter("TRANGTHAI", typeof(double));
    
            var mATRANGTHAIParameter = mATRANGTHAI != null ?
                new ObjectParameter("MATRANGTHAI", mATRANGTHAI) :
                new ObjectParameter("MATRANGTHAI", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_SYNC_UpdateTRANGTHAITBTable", iDParameter, mATBParameter, tHOIGIANParameter, mOTAParameter, tRANGTHAIParameter, mATRANGTHAIParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    }
}
